# Generated by Django 4.0.2 on 2022-05-03 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idpass', '0002_song_details_songmodel_delete_pgattribute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=90, unique=True)),
                ('cart_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='pgadd_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_quantity', models.IntegerField()),
                ('cart_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart_list')),
                ('cart_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idpass.song_details')),
            ],
        ),
    ]
