# Generated by Django 4.0.2 on 2022-05-03 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idpass', '0002_song_details_songmodel_delete_pgattribute_and_more'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pgadd_items',
            new_name='cart_items',
        ),
    ]
