# Generated by Django 4.0.2 on 2022-05-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_pgadd_items_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
