# Generated by Django 4.0.2 on 2022-05-08 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_items_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='active',
            new_name='fav',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='prodt',
            new_name='song_obj',
        ),
        migrations.RemoveField(
            model_name='items',
            name='quan',
        ),
    ]
