# Generated by Django 4.0.2 on 2022-02-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pgattribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attri1', models.CharField(max_length=30)),
                ('attri2', models.CharField(max_length=30)),
                ('attri3', models.CharField(max_length=30)),
                ('attri9', models.IntegerField()),
            ],
        ),
    ]
