# Generated by Django 4.0.2 on 2022-05-03 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idpass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='song_details',
            fields=[
                ('song_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('song_name', models.CharField(max_length=90, unique=True)),
                ('slug_field', models.SlugField(max_length=90, unique=True)),
                ('artists_name', models.CharField(max_length=90)),
                ('song_img', models.ImageField(upload_to='testimg')),
                ('description', models.TextField()),
                ('rate_song', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('mybest', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='songmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_model', models.CharField(max_length=90, unique=True)),
                ('slug_field', models.SlugField(blank=True, max_length=90, unique=True)),
            ],
            options={
                'verbose_name': 'categorry',
                'verbose_name_plural': 'categories',
                'ordering': ('song_model',),
            },
        ),
        migrations.DeleteModel(
            name='pgattribute',
        ),
        migrations.AddField(
            model_name='song_details',
            name='categorry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idpass.songmodel'),
        ),
    ]
