# Generated by Django 4.0.2 on 2022-05-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idpass', '0002_song_details_songmodel_delete_pgattribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song_details',
            name='price',
            field=models.IntegerField(default=30),
        ),
    ]
