# Generated by Django 4.0.2 on 2022-05-08 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idpass', '0004_song_details_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song_details',
            name='price',
        ),
        migrations.RemoveField(
            model_name='song_details',
            name='stock',
        ),
    ]
